//Package:
package views;

//Imports:
import javax.swing.JOptionPane;
import models.Clothing;
import models.DbManager;
import models.Footwear;
import models.Staff;

public class AddProducts extends javax.swing.JFrame
{

    //Attributes:
    private Staff loggedInStaff;
    
    /**
     * Creates new form ModifyProducts
     */
    public AddProducts(Staff staff)
    {
        loggedInStaff = staff;
        
        initComponents();//Load view
        
        //Set extra attribute input be invisible until the type of product is selected
        lblExtraAttribute.setVisible(false);
        txtExtraAttribute.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        rdoClothing = new javax.swing.JRadioButton();
        rdoFootwear = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStockLevel = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        txtExtraAttribute = new javax.swing.JTextField();
        lblExtraAttribute = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Add New Product");

        jLabel2.setText("Type Of Product:");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnGroupType.add(rdoClothing);
        rdoClothing.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoClothing.setText("Clothing");
        rdoClothing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoClothingActionPerformed(evt);
            }
        });

        btnGroupType.add(rdoFootwear);
        rdoFootwear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoFootwear.setText("Footwear");
        rdoFootwear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoFootwearActionPerformed(evt);
            }
        });

        jLabel3.setText("Name:");

        jLabel4.setText("Price:");

        jLabel5.setText("Stock Level:");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblExtraAttribute.setText("[EXTRA ATTRIBUTE]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(lblExtraAttribute)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrice)
                            .addComponent(txtStockLevel)
                            .addComponent(txtExtraAttribute, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoClothing)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rdoFootwear)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnClear))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSubmit)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdoClothing)
                    .addComponent(rdoFootwear)
                    .addComponent(btnClear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExtraAttribute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExtraAttribute))
                .addGap(19, 19, 19)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        clearFields();
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        backUp();
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        //Retrieve user input from text fields:
        String name = txtName.getText();
        String priceStr = txtPrice.getText();//Needs converting to double
        String stockLevelStr = txtStockLevel.getText();//Needs converting to int
        String extraAttribute = txtExtraAttribute.getText();//IF product is footwear needs converting to int ELSE okay
        
        //Input Verification:
        
        if(!rdoClothing.isSelected() && !rdoFootwear.isSelected())//Verify at least one radio button is selected
        {
            
            JOptionPane.showMessageDialog
            (null, "Please select the product type at the top of the page.");
            
        }
        
        else if(name.equals("") || priceStr.equals("") || stockLevelStr.equals("") || extraAttribute.equals(""))//Verify user input is not blank
        {
            
            JOptionPane.showMessageDialog
            (null, "Please fill in all the details of the new product to add it to the database.");
            
        }
        
        else
        {
            
            try//Try to convert price and stock lvl
            {
                
                double price = Double.parseDouble(priceStr);
                int stockLevel = Integer.parseInt(stockLevelStr);
                
                if(rdoClothing.isSelected())//Add clothing
                {
                    
                    Clothing clo = new Clothing(name, price, stockLevel, extraAttribute);
                    
                    //Add the new product to the database via a method in DbManager
                    DbManager db = new DbManager();
                    db.addClothing(clo);
                    
                    //Once completed the fields will revert to being blank
                    clearFields();
                    
                }
            
                else//Add footwear
                {
                    
                    try//Try to convert the extra attribute to an integer as it now represents a numerical size
                    {
                        
                        int size = Integer.parseInt(extraAttribute);//Converts String input to integer (converted back to String later, perhaps redundant?)
                        
                        Footwear fwear = new Footwear(name, price, stockLevel, size);
                        
                        //Add the new product to the database via a method in DbManager
                        DbManager db = new DbManager();
                        db.addFootwear(fwear);
                    
                        //Once completed the fields will revert to being blank
                        clearFields();
                        
                    }
                    
                    catch(Exception ex)//Error msg
                    {
                        
                        JOptionPane.showMessageDialog
                        (null, "ERROR: Unable to convert size to an integer.\n" + ex);
                        
                    }
                    
                }
                
            }
            
            catch(Exception ex)//Error msg
            {
                
                JOptionPane.showMessageDialog
                (null, "ERROR: Unable to convert both price to double and stock level to integer.\n" + ex);
                
            }
            
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void rdoClothingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoClothingActionPerformed
        
        //If clothing radio button is selected:
        lblExtraAttribute.setVisible(true);//
        txtExtraAttribute.setVisible(true);//Extra attributes input visible
        
        lblExtraAttribute.setText("Measurement:");//Rename extra attribute label to reflect change
        
    }//GEN-LAST:event_rdoClothingActionPerformed

    private void rdoFootwearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoFootwearActionPerformed
        
        //If footwear radio button is selected:
        lblExtraAttribute.setVisible(true);//
        txtExtraAttribute.setVisible(true);//Extra attributes input visible
        
        lblExtraAttribute.setText("Size:");//Rename extra attribute label to reflect change
        
    }//GEN-LAST:event_rdoFootwearActionPerformed

    //Additional Methods:
    
    public void clearFields()//Empty text fields of text
    {
        txtName.setText("");
        txtPrice.setText("");
        txtStockLevel.setText("");
        txtExtraAttribute.setText("");
    }
    
    public void backUp()//Navigate to Modify Products
    {
        ModifyProducts modifyProducts = new ModifyProducts(loggedInStaff);
        this.dispose();
        modifyProducts.setVisible(true);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                //new AddProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.ButtonGroup btnGroupType;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblExtraAttribute;
    private javax.swing.JRadioButton rdoClothing;
    private javax.swing.JRadioButton rdoFootwear;
    private javax.swing.JTextField txtExtraAttribute;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStockLevel;
    // End of variables declaration//GEN-END:variables
}
