//Package:
package views;

//Imports:
import javax.swing.JOptionPane;
import models.Clothing;
import models.DbManager;
import models.Footwear;
import models.Product;
import models.Staff;


public class EditProducts extends javax.swing.JFrame
{
    
    //Attributes:
    private Staff loggedInStaff;
    private Product product;
    
    
    public EditProducts(Staff staff, Product productToEdit)
    {
        
        loggedInStaff = staff;
        product = productToEdit;

        initComponents();//Load view

        //Display appropriate values in text fields
        txtId.setText(String.valueOf(product.getProductId()));
        txtName.setText(product.getProductName());
        txtPrice.setText(String.valueOf(product.getPrice()));
        txtStockLevel.setText(String.valueOf(product.getStockLevel()));
        
        //Determine whether the product to edit is clothing or footwear and display an appropriate last attribute
        if(product.getClass().getName().equals("models.Clothing"))
        {
            //Display extra attribute label apropriately
            lblExtraAttribute.setText("Measurement: ");
            
            //Display text in the extra attribute
            Clothing clothing = (Clothing)product;
            txtExtraAttribute.setText(String.valueOf(clothing.getMeasurement()));
        }
        else
        {
            //Display extra attribute label apropriately
            lblExtraAttribute.setText("Size: ");
            
            //Display text in the extra attribute
            Footwear footwear = (Footwear)product;
            txtExtraAttribute.setText(String.valueOf(footwear.getSize()));
        }
        
        //Disallow users from editting ID text field
        txtId.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtStockLevel = new javax.swing.JTextField();
        txtExtraAttribute = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblExtraAttribute = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        btnUndo = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        LBL_CURRENCY = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID: ");

        jLabel2.setText("Name: ");

        jLabel3.setText("Price: ");

        jLabel4.setText("Stock Level: ");

        lblExtraAttribute.setText("[EXTRA ATT]");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Edit Products");

        btnUndo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btnUndo.setText("Undo");
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        LBL_CURRENCY.setText("£");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUndo)
                                .addGap(0, 3, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblExtraAttribute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtExtraAttribute)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LBL_CURRENCY)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtStockLevel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btnUndo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(LBL_CURRENCY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStockLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExtraAttribute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExtraAttribute))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSubmit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //  ==========  ACTIONS ==========
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        //Go back to the main menu while retaining logged in staff member
        ModifyProducts modifyProducts = new ModifyProducts(loggedInStaff);
        this.dispose();
        modifyProducts.setVisible(true);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        
        resetFields();
        
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        
        //Recieve user input:
        String name = txtName.getText();
        String price = txtPrice.getText();
        String stockLevel = txtStockLevel.getText();
        String extraAttribute = txtExtraAttribute.getText();
        
        /*
        ==========  INPUT VERIFICATION  ==========
        */
        
        //Makes sure fields are not blank:
        if(name.equals("") || price.equals("") || stockLevel.equals("") || extraAttribute.equals(""))
        {
            JOptionPane.showMessageDialog(null, "ERROR: Please complete all fields.");
        }

        else
        {
            //TRY to convert String price to double
            try
            {
                
                double doublePrice = Double.parseDouble(price);
                
                //TRY to convert String stock level to int
                try
                {
                    
                    int intStockLevel = Integer.parseInt(stockLevel);
                    
                    //TRY to edit product and save changes
                    try
                    {
                        if(product.getClass().getName().equals("models.Clothing"))
                        {
                            Clothing clothing = new Clothing(name, doublePrice, intStockLevel, extraAttribute);
                            
                            clothing.setProductId(product.getProductId());//Retrieve and set product ID to the one being edited
                            
                            DbManager db = new DbManager();
                            db.editProduct(clothing);

                            product = clothing; //Update product global variable
                            
                            //CLOTHING SUCCESSFULLY UPDATED!
                            
                            resetFields();
                        }
                        else
                        {
                            try//to convert the extra attribute to an integer
                            {
                                int size = Integer.parseInt(extraAttribute);
                                
                                try//to edit the footwear product and save changes
                                {
                                    Footwear footwear = new Footwear(name, doublePrice, intStockLevel, size);
                                    
                                    footwear.setProductId(product.getProductId());//Retrieve and set product ID to the one being edited
                            
                                    DbManager db = new DbManager();
                                    db.editProduct(footwear);
                            
                                    product = footwear; //Update product global variable
                                    
                                    //FOOTWEAR SUCCESSFULLY UPDATED!
                            
                                    resetFields();
                                }
                                catch(Exception ex)//Error Msg
                                {
                                    JOptionPane.showMessageDialog(null, "ERROR: Unable to edit footwear!" + ex);
                                }
                                
                            }
                            catch(Exception ex)//Error Msg
                            {
                                JOptionPane.showMessageDialog
                                (null, "ERROR: Unable to convert Size to a number. Make sure to type Size as a number only!\n" + ex);
                            }
                             
                        }
                    }
                    catch(Exception ex)//Error Msg
                    {
                        JOptionPane.showMessageDialog(null, "ERROR: Cannot determine if the product is clothing or footwear.\n" + ex);
                    }
                    
                }
                catch(Exception ex)//Error Msg
                {
                    JOptionPane.showMessageDialog(null, "Please input a number for the Stock Level.");
                }
                
            }
            catch(Exception ex)//Error Msg
            {
                JOptionPane.showMessageDialog(null, "Please input a number for the Price.");
            }
            
        }
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    public void resetFields()
    {
        //Display appropriate values in text fields
        txtId.setText(String.valueOf(product.getProductId()));
        txtName.setText(product.getProductName());
        txtPrice.setText(String.valueOf(product.getPrice()));
        txtStockLevel.setText(String.valueOf(product.getStockLevel()));
        
        //Determine whether the product to edit is clothing or footwear and display an appropriate last attribute
        if(product.getClass().getName().equals("models.Clothing"))
        {
            //Display text in the extra attribute
            Clothing clothing = (Clothing)product;
            txtExtraAttribute.setText(String.valueOf(clothing.getMeasurement()));
        }
        else
        {
            //Display text in the extra attribute
            Footwear footwear = (Footwear)product;
            txtExtraAttribute.setText(String.valueOf(footwear.getSize()));
        }
    }
    
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                //EMPTY
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL_CURRENCY;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUndo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblExtraAttribute;
    private javax.swing.JTextField txtExtraAttribute;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStockLevel;
    // End of variables declaration//GEN-END:variables
}