//Package:
package views;

//Imports:
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Customer;
import models.Order;
import models.OrderLine;
import models.Product;


public class ViewBasket extends javax.swing.JFrame
{

    //Attributes:
    private Customer loggedInCustomer;
    private Order currentOrder;
    
    public ViewBasket(Customer customer)
    {
        loggedInCustomer = customer;
        currentOrder = loggedInCustomer.findLatestOrder();
        
        initComponents();//Load view
        
        //Load table details
        DefaultTableModel basketModel = (DefaultTableModel)tblBasket.getModel();
        
        for(Map.Entry<Integer, OrderLine> olEntry : currentOrder.getOrderLines().entrySet())
        {
            OrderLine orderLine = olEntry.getValue();
            Product product = orderLine.getProduct();
            
            basketModel.addRow(new Object[]
            {product.getProductId(),
                product, 
                String.format("%.02f",product.getPrice()),
                orderLine.getQuantity()});
        }
                
        lblTotal.setText(String.format("%.02f", currentOrder.getOrderTotal()));//Load total price
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBasket = new javax.swing.JTable();
        btnRemoveProduct = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        LBL_TOTAL = new javax.swing.JLabel();
        btnPurchase = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBasket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(tblBasket);

        btnRemoveProduct.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnRemoveProduct.setText("Remove Item");
        btnRemoveProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveProductActionPerformed(evt);
            }
        });

        lblTotal.setText("[TOTAL PRICE]");

        LBL_TOTAL.setText("Total: £");

        btnPurchase.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnPurchase.setText("Purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnRemoveProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LBL_TOTAL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPurchase))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBack))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotal)
                        .addComponent(LBL_TOTAL))
                    .addComponent(btnRemoveProduct))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPurchase)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveProductActionPerformed
        
        int selectedRow = tblBasket.getSelectedRow();//Retrieve user selection
        
        if(selectedRow == -1)//Nothing selected
        {
            JOptionPane.showMessageDialog
            (null, "Please select the product you wish to delete.");
        }
        
        else//Something IS selected
        {
            
            int productId = Integer.parseInt(String.valueOf(tblBasket.getValueAt(selectedRow, 0)));
            
            currentOrder.removeOrderLine(productId);//Remove from db
            
            JOptionPane.showMessageDialog
            (null, "Product removed from basket successfully!");//Confirmation msg
            
            //Remove from table
            DefaultTableModel basketModel = (DefaultTableModel)tblBasket.getModel();
            basketModel.removeRow(selectedRow);
            tblBasket.setModel(basketModel);
            
            lblTotal.setText(String.format("%.02f", currentOrder.getOrderTotal()));//Update total cost
        }
        
    }//GEN-LAST:event_btnRemoveProductActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
        
        if(currentOrder.getOrderLines().isEmpty())//Basket is empty
        {
            JOptionPane.showMessageDialog(null, "Your basket is currently empty.");
        }
        
        else
        {
            
            boolean canBuy = true;//Initialise canBuy bool
            
            for(Map.Entry<Integer, OrderLine> olEntry : currentOrder.getOrderLines().entrySet())//For each product in basket...
            {
                OrderLine ol = olEntry.getValue();
                
                //Check the stock level for each product
                if((ol.getProduct().getStockLevel()) < ol.getQuantity())//Product is out of stock
                {
                    canBuy = false;
                    JOptionPane.showMessageDialog
                    (null, "The product " + ol.getProduct().getProductId() + " is out of stock!");                   
                }
            }
            
            if(canBuy)//Runs if all products found in stock
            {
                currentOrder.completeOrder();//Label order as complete in db
                
                //Navigate to the Order Confirmation view
                OrderConfirmation confirmation = new OrderConfirmation(loggedInCustomer, currentOrder);
                this.dispose();
                confirmation.setVisible(true);
            }
        }
        
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        //Navigate back to View Products page
        ViewProducts viewProducts = new ViewProducts(loggedInCustomer);
        this.dispose();
        viewProducts.setVisible(true);
        
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBasket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                //EMPTY
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBL_TOTAL;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JButton btnRemoveProduct;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblBasket;
    // End of variables declaration//GEN-END:variables
}
